services:
  keenetic-monitoring:
    build: .
    container_name: keenetic-monitoring
    env_file:
      - .env
#    volumes:
#      - ./config/metrics.json:/home/config/metrics.json:ro
    ports:
      - 9100:9100